USE [master]
GO

/****** Object:  Database [Borg]    Script Date: 12/12/2009 08:38:53 ******/
CREATE DATABASE [Borg] ON  PRIMARY 
( NAME = N'Borg', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL.1\MSSQL\DATA\Borg_1.ndf' , SIZE = 4048KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Borg_Log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL.1\MSSQL\DATA\Borg_2.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 1024KB )
GO

ALTER DATABASE [Borg] SET COMPATIBILITY_LEVEL = 90
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Borg].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO

ALTER DATABASE [Borg] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Borg] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Borg] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Borg] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Borg] SET ARITHABORT OFF 
GO

ALTER DATABASE [Borg] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Borg] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Borg] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Borg] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Borg] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Borg] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Borg] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Borg] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Borg] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Borg] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Borg] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Borg] SET AUTO_UPDATE_STATISTICS_ASYNC ON 
GO

ALTER DATABASE [Borg] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Borg] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Borg] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Borg] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Borg] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Borg] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Borg] SET  READ_WRITE 
GO

ALTER DATABASE [Borg] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Borg] SET  MULTI_USER 
GO

ALTER DATABASE [Borg] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Borg] SET DB_CHAINING OFF 
GO


